### ISSUE TITLE
error when my bot starts

### ISSUE THREAD

**Issue by OmarA32** [pipebits/image-search-engine#2]
(my bot folder)/node_modules/image-search-engine/src/optionsManager.js:12
    if(options?.size){
               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/final-kitten/node_modules/image-search-engine/src/request.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/final-kitten/node_modules/image-search-engine/index.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Comment by snack-ie** [comment]
i have been getting the same error

**Comment by pipebits** [comment]
You have to use a version higher than 14 of node, if you are not using it I recommend updating
